/**
 * Country flag mapping utility
 * Maps 3-letter country codes to ESPN country flag URLs
 */

export const getCountryFlagUrl = (countryCode: string): string => {
  const code = countryCode.toLowerCase();
  
  // ESPN country flag URL pattern: https://a.espncdn.com/i/teamlogos/countries/500/{code}.png
  return `https://a.espncdn.com/i/teamlogos/countries/500/${code}.png`;
};

export const getCountryFlagAlt = (countryCode: string): string => {
  const code = countryCode.toLowerCase();
  const countryNames: Record<string, string> = {
    'chn': 'China',
    'tha': 'Thailand', 
    'kor': 'South Korea',
    'fra': 'France',
    'swe': 'Sweden',
    'tpo': 'Chinese Taipei',
    'twn': 'Taiwan',
    'usa': 'United States',
    'zaf': 'South Africa',
    'jpn': 'Japan',
    'aus': 'Australia',
    'can': 'Canada',
    'gbr': 'Great Britain',
    'irl': 'Ireland',
    'nzl': 'New Zealand',
    'nor': 'Norway',
    'den': 'Denmark',
    'fin': 'Finland',
    'ger': 'Germany',
    'ita': 'Italy',
    'esp': 'Spain',
    'nld': 'Netherlands',
    'bel': 'Belgium',
    'aut': 'Austria',
    'che': 'Switzerland',
    'pol': 'Poland',
    'cze': 'Czech Republic',
    'svk': 'Slovakia',
    'hun': 'Hungary',
    'rou': 'Romania',
    'bul': 'Bulgaria',
    'hrv': 'Croatia',
    'srb': 'Serbia',
    'bih': 'Bosnia and Herzegovina',
    'mne': 'Montenegro',
    'mkd': 'North Macedonia',
    'alb': 'Albania',
    'grc': 'Greece',
    'cyp': 'Cyprus',
    'mlt': 'Malta',
    'isl': 'Iceland',
    'lva': 'Latvia',
    'ltu': 'Lithuania',
    'est': 'Estonia',
    'blr': 'Belarus',
    'ukr': 'Ukraine',
    'mda': 'Moldova',
    'rus': 'Russia',
    'kaz': 'Kazakhstan',
    'uzb': 'Uzbekistan',
    'kgz': 'Kyrgyzstan',
    'tjk': 'Tajikistan',
    'tkm': 'Turkmenistan',
    'afg': 'Afghanistan',
    'pak': 'Pakistan',
    'ind': 'India',
    'bng': 'Bangladesh',
    'lka': 'Sri Lanka',
    'mdv': 'Maldives',
    'npl': 'Nepal',
    'btn': 'Bhutan',
    'mmr': 'Myanmar',
    'lao': 'Laos',
    'khm': 'Cambodia',
    'vnm': 'Vietnam',
    'mys': 'Malaysia',
    'sgp': 'Singapore',
    'idn': 'Indonesia',
    'phl': 'Philippines',
    'brn': 'Brunei',
    'tls': 'East Timor',
    'mng': 'Mongolia',
    'prk': 'North Korea',
    'mex': 'Mexico',
    'gtm': 'Guatemala',
    'blz': 'Belize',
    'slv': 'El Salvador',
    'hnd': 'Honduras',
    'nic': 'Nicaragua',
    'cri': 'Costa Rica',
    'pan': 'Panama',
    'cub': 'Cuba',
    'jam': 'Jamaica',
    'hti': 'Haiti',
    'dom': 'Dominican Republic',
    'pri': 'Puerto Rico',
    'tto': 'Trinidad and Tobago',
    'bhs': 'Bahamas',
    'brb': 'Barbados',
    'lca': 'Saint Lucia',
    'vct': 'Saint Vincent and the Grenadines',
    'grd': 'Grenada',
    'dma': 'Dominica',
    'kna': 'Saint Kitts and Nevis',
    'atg': 'Antigua and Barbuda',
    'col': 'Colombia',
    'ven': 'Venezuela',
    'guy': 'Guyana',
    'sur': 'Suriname',
    'bra': 'Brazil',
    'ecu': 'Ecuador',
    'per': 'Peru',
    'bol': 'Bolivia',
    'par': 'Paraguay',
    'ury': 'Uruguay',
    'arg': 'Argentina',
    'chl': 'Chile',
    'egy': 'Egypt',
    'lby': 'Libya',
    'tun': 'Tunisia',
    'dza': 'Algeria',
    'mar': 'Morocco',
    'sdn': 'Sudan',
    'ssd': 'South Sudan',
    'eth': 'Ethiopia',
    'eri': 'Eritrea',
    'dji': 'Djibouti',
    'som': 'Somalia',
    'ken': 'Kenya',
    'uga': 'Uganda',
    'tza': 'Tanzania',
    'rwa': 'Rwanda',
    'bdi': 'Burundi',
    'mwi': 'Malawi',
    'zmb': 'Zambia',
    'zwe': 'Zimbabwe',
    'bwa': 'Botswana',
    'nam': 'Namibia',
    'zaf': 'South Africa',
    'lso': 'Lesotho',
    'swz': 'Eswatini',
    'moz': 'Mozambique',
    'mdg': 'Madagascar',
    'mus': 'Mauritius',
    'syc': 'Seychelles',
    'com': 'Comoros',
    'mrt': 'Mauritania',
    'sen': 'Senegal',
    'gmb': 'Gambia',
    'gnb': 'Guinea-Bissau',
    'gin': 'Guinea',
    'sle': 'Sierra Leone',
    'lbr': 'Liberia',
    'civ': 'Ivory Coast',
    'gha': 'Ghana',
    'tgo': 'Togo',
    'ben': 'Benin',
    'bfa': 'Burkina Faso',
    'mli': 'Mali',
    'ner': 'Niger',
    'nga': 'Nigeria',
    'cmr': 'Cameroon',
    'tcd': 'Chad',
    'caf': 'Central African Republic',
    'cod': 'Democratic Republic of the Congo',
    'cog': 'Republic of the Congo',
    'gab': 'Gabon',
    'gnq': 'Equatorial Guinea',
    'stp': 'São Tomé and Príncipe',
    'ago': 'Angola'
  };
  
  return countryNames[code] || countryCode.toUpperCase();
};
