version: '3.8'

services:
  lpga-api:
    build: .
    container_name: birdie-briefing-lpga-api
    restart: unless-stopped
    ports:
      - "8585:8585"
    environment:
      - FLASK_ENV=production
      - FLASK_DEBUG=false
      - PORT=8585
      - HOST=0.0.0.0
      - DATABASE_URL=sqlite:///espn_API.db?check_same_thread=False
      - LOG_LEVEL=INFO
      - MAX_CONCURRENT_REQUESTS=10
      - REQUEST_TIMEOUT=30
    volumes:
      - ./instance:/app/instance
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8585/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - lpga-network

  nginx:
    image: nginx:alpine
    container_name: birdie-briefing-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - lpga-api
    networks:
      - lpga-network

networks:
  lpga-network:
    driver: bridge

volumes:
  instance-data:
  logs:
