name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    # Skip build if commit message contains [skip ci]
    if: ${{ !contains(github.event.head_commit.message, '[skip ci]') }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build with Next.js
        env:
          NEXT_PUBLIC_TRANSLATION_WIDGET_KEY: ${{ secrets.NEXT_PUBLIC_TRANSLATION_WIDGET_KEY }}
        run: |
          # Skip image optimization if this is a rankings update commit
          if [[ "${{ github.event.head_commit.message }}" == "Update rankings data"* ]] || [[ "${{ github.event.head_commit.message }}" == *"rankings"* ]]; then
            echo "🔄 Rankings update detected - skipping image optimization"
            npm run build:no-optimize
          else
            echo "🏗️ Regular build - running with image optimization"
            npm run build
          fi

      - name: Add .nojekyll file
        run: touch out/.nojekyll

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './out'

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
